name: Deploy 

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == "workflow_dispatch" || contains(github.event.head_commit.message, '[deploy]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/devcontainers/ci/blob/main/docs/github-action.md
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          imageName: ghcr.io/${{ github.repository }}
          runCmd: make deploy
          env: |
            NETLIFY_AUTH_TOKEN=${{secrets.NETLIFY_AUTH_TOKEN}}
            NETLIFY_SITE_ID=${{secrets.NETLIFY_SITE_ID}}